name: websocket
description: Universal package for websocket, compatible with web, flutter, and vm.
version: 0.0.5
author: TruongSinh Tran-Nguyen <i@truongsinh.pro>
homepage: https://github.com/truongsinh/dart-websocket

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: any
  test_coverage: any
  stream_channel: any
